#!/usr/bin/env python3
"""
Build `docs/typos.md` — the canonical record of every typo and consistency problem known in this
repository.

Three things feed it:

  1. `docs/naming_audit.md`, the declaration audit (categories prefixed `NAME-` here);
  2. `docs/comment_audit.md`, the comment and docstring audit (prefixed `DOC-`);
  3. the source modules in `scripts/typo_audit/sources/`, one per surface that neither of those two
     ever reads — Lean string literals, the Lean trees outside `Mathlib/`, path components,
     repository markdown and CI files, the `docs/*.yaml` data files and `references.bib`,
     deprecation metadata, and the notation vocabulary.

The first two are read from their generated markdown rather than re-run, because each takes several
minutes; pass `--regen` to run them first. The source modules are always run.

`docs/typos.md` is a living document in the same sense as the audits it absorbs: every row carries a
`Status` and a `Note`, and re-running preserves whatever has been written into them while adding new
rows as `open` and dropping rows that no longer apply. Triage happens by editing the file.

Usage:
    python3 scripts/typo_audit/typos.py [--root .] [--regen] [--only MODULE ...]
"""
from __future__ import annotations

import argparse
import collections
import datetime
import importlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "sources"))

from context import Context  # noqa: E402

CELL = re.compile(r"(?<!\\)\|")
STATUSES = ("open", "confirmed", "fp", "fixed", "wontfix")

# Where each group of categories comes from, and the prefix its ids get in the combined document.
UPSTREAM = [
    ("NAME", "naming_audit.md", "Declaration names",
     "Findings about the names of declarations themselves — casing, Lean 3 spellings, outdated "
     "components, names that disagree with their statements. Generated by "
     "`scripts/naming_audit/naming_audit.py`."),
    ("DOC", "comment_audit.md", "Comments and docstrings",
     "Findings about the prose around declarations — section headings, cross-references that no "
     "longer resolve, spelling and markup conventions. Generated by "
     "`scripts/comment_audit/comment_audit.py`."),
]

# Source module -> (prefix, section title). Order is the order of the sections in the document.
SOURCES = [
    ("lean_strings", "STR", "Lean string literals"),
    ("wider_lean", "TREE", "Lean trees outside Mathlib"),
    ("paths", "PATH", "File and directory names"),
    ("plaintext", "TEXT", "Markdown, scripts and CI files"),
    ("docsdata", "DATA", "Curated data files and the bibliography"),
    ("deprecations", "DEP", "Deprecation metadata"),
    ("notation", "VOCAB", "Library notes and notation vocabulary"),
]


def parse_audit(path: str, prefix: str) -> tuple:
    """Rows and category titles from one generated audit document."""
    rows, titles, cat = [], collections.OrderedDict(), None
    if not os.path.exists(path):
        print(f"warning: {path} not found, skipping", file=sys.stderr)
        return rows, titles
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"### ([A-Z]\d+): (.+)", line)
            if m:
                cat = f"{prefix}-{m.group(1)}"
                titles[cat] = m.group(2).strip()
                continue
            if cat is None or not line.startswith("| "):
                continue
            cells = [c.strip() for c in CELL.split(line.rstrip("\n"))[1:-1]]
            if len(cells) < 5 or cells[0] not in STATUSES:
                continue
            loc = cells[2].strip("`")
            file, _, lineno = loc.rpartition(":")
            rows.append({"cat": cat, "status": cells[0], "name": cells[1].strip("`"),
                         "file": file or loc, "line": int(lineno) if lineno.isdigit() else 0,
                         "detail": cells[3], "note": cells[4]})
    return rows, titles


def row_key(cat: str, name: str, file: str, detail: str) -> str:
    """Stable identity of a row across runs: line numbers move, this does not."""
    quoted = re.findall(r"`([^`]*)`", detail)
    tail = quoted[-1] if quoted else ""
    return f"{cat}|{name}|{file}|{tail}"


def read_existing(path: str) -> dict:
    out, cat = {}, None
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"### ([A-Z]+-[A-Z]?\d+): ", line)
            if m:
                cat = m.group(1)
                continue
            if cat is None or not line.startswith("| "):
                continue
            cells = [c.strip() for c in CELL.split(line.rstrip("\n"))[1:-1]]
            if len(cells) >= 5 and cells[0] in STATUSES:
                loc = cells[2].strip("`")
                file = loc.rpartition(":")[0] or loc
                out[row_key(cat, cells[1].strip("`"), file, cells[3])] = (cells[0], cells[4])
    return out


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def anchor(cat: str, title: str) -> str:
    return re.sub(r"[^\w\- ]", "", f"{cat}: {title}".lower()).replace(" ", "-")


def render(groups, existing, out_path, stats):
    today = datetime.date.today().isoformat()
    all_rows = [r for _g, _t, _d, cats in groups for _c, _ct, rows in cats for r in rows]
    status_of = {}
    for r in all_rows:
        r["key"] = row_key(r["cat"], r["name"], r["file"], r["detail"])
        # This document's own triage wins; failing that, a row absorbed from one of the two audits
        # keeps the verdict already recorded there, so that moving to `typos.md` does not throw
        # away work someone has already done by hand.
        status_of[r["key"]] = existing.get(
            r["key"], (r.get("status", "open"), r.get("note", "")))
    dropped = sum(1 for k in existing if k not in status_of)
    counts = collections.Counter(status_of[r["key"]][0] for r in all_rows)

    L = []
    L.append("# Mathlib typos")
    L.append("")
    L.append(f"_Generated by `scripts/typo_audit/typos.py` on {today}. "
             f"{len(all_rows)} findings across {len({r['file'] for r in all_rows})} files._")
    L.append("")
    L.append("The canonical record of every typo and consistency problem known in this repository.")
    L.append("Each finding is one row. Rows are identified by their category, token and file — not by")
    L.append("line number — so re-running the generator keeps whatever you have written into the")
    L.append("`Status` and `Note` columns, adds new findings as `open`, and drops findings that no")
    L.append("longer apply. **Triage by editing this file.**")
    L.append("")
    L.append("Statuses: `open` (not yet looked at), `confirmed` (checked by hand, should be fixed),")
    L.append("`fp` (false positive or accepted exception), `fixed` (corrected; the row disappears on")
    L.append("the next run), `wontfix` (real but deliberately left alone). Confidence (`conf`) is the")
    L.append("scanner's own estimate, not a triage verdict.")
    L.append("")
    L.append(f"Current triage: **{counts['open']} open**, {counts['confirmed']} confirmed, "
             f"{counts['fp']} false positives, {counts['wontfix']} wontfix.")
    L.append("")
    L.append("[`tickets.md`](tickets.md) turns the open rows here into batches sized for individual")
    L.append("pull requests. Re-generate it whenever this file changes.")
    L.append("")
    L.append("## How a finding gets here")
    L.append("")
    L.append("Every surface is judged against the same yardstick: the vocabulary of Mathlib's own")
    L.append("comments. A word is reported only when the corpus never uses it, a dictionary does not")
    L.append("know it, it is not an identifier, it is not a regular derivative of a common word, and")
    L.append("some frequent word is one edit away. The corpus is built from comments under `Mathlib/`,")
    L.append("`Archive/` and `Counterexamples/` only, never from the surface being audited, so a typo")
    L.append("cannot vote itself into the dictionary. Everything that could otherwise be a matter of")
    L.append("taste — which spelling, which heading, which capitalisation — is settled by counting how")
    L.append("the rest of the library writes it, and those counts are in the `Detail` column.")
    L.append("")
    L.append("## Sections")
    L.append("")
    L.append("| Section | Where the findings come from | Categories | Findings |")
    L.append("|---|---|---:|---:|")
    for prefix, title, desc, cats in groups:
        n = sum(len(rows) for _c, _ct, rows in cats)
        L.append(f"| [{title}](#{re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')}) | "
                 f"`{prefix}-*` | {len(cats)} | {n} |")
    L.append("")
    L.append("## Summary")
    L.append("")
    L.append("| Category | Description | Rows | open | confirmed | fp | wontfix |")
    L.append("|---|---|---:|---:|---:|---:|---:|")
    for _prefix, _title, _desc, cats in groups:
        for cat, ctitle, rows in cats:
            c = collections.Counter(status_of[r["key"]][0] for r in rows)
            L.append(f"| [{cat}](#{anchor(cat, ctitle)}) | {ctitle} | {len(rows)} | "
                     f"{c['open']} | {c['confirmed']} | {c['fp']} | {c['wontfix']} |")
    L.append("")
    if dropped:
        L.append(f"_{dropped} row(s) from the previous version no longer apply and were dropped._")
        L.append("")

    status_rank = {"confirmed": 0, "open": 1, "wontfix": 2, "fixed": 3, "fp": 4}
    conf_rank = {"high": 0, "medium": 1, "low": 2}
    for prefix, title, desc, cats in groups:
        L.append(f"## {title}")
        L.append("")
        L.append(desc)
        L.append("")
        for cat, ctitle, rows in cats:
            L.append(f"### {cat}: {ctitle}")
            L.append("")
            L.append(f"{len(rows)} row(s).")
            L.append("")
            if not rows:
                continue
            rows.sort(key=lambda r: (status_rank[status_of[r["key"]][0]],
                                     conf_rank.get(r.get("conf", "medium"), 1),
                                     r["file"], r["line"], r["name"]))
            L.append("| Status | Finding | Location | Detail | Note |")
            L.append("|---|---|---|---|---|")
            for r in rows:
                st, note = status_of[r["key"]]
                conf = r.get("conf")
                detail = r["detail"] if r["detail"].startswith("(") else f"({conf}) {r['detail']}"
                L.append(f"| {st} | `{md_escape(r['name'])}` | `{r['file']}:{r['line']}` | "
                         f"{md_escape(detail)} | {md_escape(note)} |")
            L.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    return status_of


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--out", default=None)
    ap.add_argument("--regen", action="store_true",
                    help="re-run the naming and comment audits first (several minutes each)")
    ap.add_argument("--only", nargs="*", default=None, help="run only these source modules")
    args = ap.parse_args()
    root = os.path.abspath(args.root)
    out = args.out or os.path.join(root, "docs", "typos.md")

    if args.regen:
        for script in ("scripts/naming_audit/naming_audit.py", "scripts/comment_audit/comment_audit.py"):
            print(f"running {script} ...")
            subprocess.run([sys.executable, os.path.join(root, script), "--root", root], check=True)

    groups = []
    for prefix, fname, title, desc in UPSTREAM:
        rows, titles = parse_audit(os.path.join(root, "docs", fname), prefix)
        by_cat = collections.OrderedDict((c, []) for c in titles)
        for r in rows:
            by_cat[r["cat"]].append(r)
        groups.append((prefix, title, desc, [(c, titles[c], by_cat[c]) for c in titles]))
        print(f"{title}: {len(rows)} rows in {len(titles)} categories")

    wanted = set(args.only) if args.only else None
    ctx = None
    for modname, prefix, title in SOURCES:
        if wanted is not None and modname not in wanted:
            continue
        path = os.path.join(HERE, "sources", modname + ".py")
        if not os.path.exists(path):
            print(f"warning: source module {modname} not written yet, skipping", file=sys.stderr)
            continue
        if ctx is None:
            print("building the corpus ...")
            ctx = Context(root, verbose=True)
        mod = importlib.import_module(modname)
        try:
            found = mod.collect(ctx)
        except Exception as e:  # one broken surface must not cost the whole document
            print(f"warning: source module {modname} failed: {e!r}", file=sys.stderr)
            continue
        for f in found:
            f["cat"] = f"{prefix}-{f['cat']}"
        by_cat = collections.OrderedDict(
            (f"{prefix}-{c}", t) for c, t in getattr(mod, "CATEGORIES", {}).items())
        rows_by_cat = collections.OrderedDict((c, []) for c in by_cat)
        for f in found:
            rows_by_cat.setdefault(f["cat"], []).append(f)
            by_cat.setdefault(f["cat"], f["cat"])
        groups.append((prefix, title, mod.__doc__.strip().split("\n\n")[0],
                       [(c, by_cat[c], rows_by_cat[c]) for c in by_cat]))
        print(f"{title}: {len(found)} rows in {len(by_cat)} categories")

    existing = read_existing(out)
    status_of = render(groups, existing, out, {})
    total = sum(len(rows) for _p, _t, _d, cats in groups for _c, _ct, rows in cats)
    print(f"\n{total} findings -> {out}")
    c = collections.Counter(v[0] for v in status_of.values())
    print(f"  open={c['open']} confirmed={c['confirmed']} fp={c['fp']} wontfix={c['wontfix']}")


if __name__ == "__main__":
    main()
