#!/usr/bin/env python3
"""
The curated data files under `docs/`: the four YAML theorem/topic lists and `docs/references.bib`.

These files are prose, but they are not comments, so no other surface of the audit looks at them:
the comment scanner never opens them, and the only thing it ever asks of `references.bib` is
whether a cited key exists — it never reads an entry.  Yet they are among the most-read pages
mathlib publishes: `100.yaml`, `1000.yaml`, `overview.yaml` and `undergrad.yaml` are rendered as
the community website's status tables, and every `## References` link resolves into
`references.bib`.

What counts as prose here is decided structurally rather than by guessing:

* in `100.yaml` and `1000.yaml` the entries are machine keys (`Q132469`), so only the `title:`,
  `comment:` and `note:` values are read;
* in `overview.yaml` and `undergrad.yaml` it is the other way round — the *keys* are the English
  topic names ("existence of bases") and the values are declaration names, so the keys are read
  and the values are not;
* every `#` line comment is read in all four;
* in `references.bib` only `title`, `publisher`, `journal`, `series`, `note` and `booktitle` are
  read, plus the file's own header comment.  `author` is skipped entirely: a name list is not
  English prose.

`ctx.suggest` makes the spelling judgement, as everywhere else in the audit.  Three checks it does
not cover are added here:

* **doubled words** ("will will change") — a structural check, no dictionary involved;
* **lowercased proper nouns** (`laplacian` for `Laplacian`) — `ctx.suggest` cannot see these,
  because its counter is lowercased and so the word is "known".  The evidence used instead is a
  case census of the corpus' own comments: a word Mathlib's prose writes capitalised at least 20
  times and never writes in lowercase is a proper noun, and a lowercase use of it in a curated
  file is a slip.  The census reads the corpus a second time, which costs about a minute; it is
  worth it because nothing cheaper tells a surname from a word, and it is decisive — of the 685
  words it was asked about, exactly one survived;
* **structural checks on the bibliography**: an entry nothing cites, and two entries that are the
  same document under different keys.

Deliberately not checked, for precision:

* **capitalised words**, for the spelling check.  Roughly a thousand of the distinct words here
  are surnames, `100.yaml` writes its titles in Title Case, and a surname the corpus does not
  happen to use is one edit from an English word often enough to sink the category: dropping the
  guard adds thirty findings, every one of them a false positive (`Bondy`, `Gelfond`, `Ringel`,
  `Picone`, `Golod`, `Wille`, the journal abbreviations `Comput.` and `Relat.`, and the German
  and Latin `Informatik`, `Spektrum`, `Compositio`, `Universalis`).  Lowercase words are
  ordinary English and are checked normally.
* **non-English bibliography values.**  Roughly a tenth of the entries have French, German or
  Russian titles, and a French word is regularly one edit from an English one.  A value is only
  spell-checked when Mathlib's own prose knows at least half of its words, which is what keeps
  `familles`, `commutatifs`, `langage`, `cercle`, `reine` and `unter` out of the report; all
  eight words the guard discards are false positives of exactly that kind.  It also puts the
  misspelt `colloboration` in "avec la colloboration de {J}. {Dieudonn{\\'e}}" out of reach,
  though that one is unreachable anyway: Mathlib's comments use `collaboration` once, far under
  the twenty uses `ctx.suggest` requires of a correction.
* **British spellings.**  `factorisation` in `overview.yaml` names `UniqueFactorizationMonoid`,
  but Mathlib's own comments write `factorisation` 120 times against `factorization` 246, and
  these four files use both (`formalis*` nine times, `formaliz*` four).  Which one to prefer is
  a style decision for the library, not a spelling mistake this audit can assert.
* **`decl:` fields naming a declaration that no longer exists.**  `scripts/check-yaml.lean` runs
  in CI and answers exactly this question against the real Lean environment.  A textual parse
  cannot: matching the 1,273 declaration references in these files against
  `naming_audit.extract_tree` calls five of them missing, and all five exist — `norm_add_le` is
  generated by `@[to_additive]`, `Nat` belongs to core rather than to this tree, and
  `Complex.isAlgClosed`, `NumberField.Units.basisModTorsion` and
  `NumberField.Units.exist_unique_eq_mul_prod` are simply parsed over.  The category would be
  100% false positives.
* **grammar**, such as the "will silently errors" in the bibliography's own header.  Nothing here
  can tell a wrong verb form from a right one ("will process", "may cross") without a parser.
"""
from __future__ import annotations

import collections
import os
import re
import unicodedata

import prose_typos as pt
from context import Finding, line_of, excerpt

SURFACE = "curated docs data files"

CATEGORIES = {
    "Y1": "Probable spelling errors in the YAML data files",
    "Y2": "Doubled words",
    "Y3": "Proper nouns written in lowercase",
    "Y4": "Probable spelling errors in references.bib",
    "Y5": "Bibliography entries that nothing cites",
    "Y6": "Bibliography entries duplicating another entry",
}

YAML_FILES = ("docs/100.yaml", "docs/1000.yaml", "docs/overview.yaml", "docs/undergrad.yaml")
BIB_FILE = "docs/references.bib"
# `100.yaml` and `1000.yaml` are keyed by theorem number / wikidata id, and carry their prose in
# fields; `overview.yaml` and `undergrad.yaml` are keyed by topic name and carry it in the keys.
KEYED_BY_TOPIC = ("docs/overview.yaml", "docs/undergrad.yaml")
PROSE_FIELDS = ("title", "comment", "note")
BIB_PROSE_FIELDS = ("title", "publisher", "journal", "series", "note", "booktitle")

# `key:` or `key: value`, with the key optionally quoted (`"$p$-adic number": 'Padic'`).  The
# files are written by hand but stay within this shape: no block scalars, no folded values.
YAML_LINE = re.compile(r"^[ ]*(?P<key>\"[^\"]*\"|'[^']*'|[^:#\n]+?)[ ]*:"
                       r"(?:[ ]+(?P<val>.*\S))?[ ]*$")
YAML_COMMENT = re.compile(r"^[ ]*#[ ]?(?P<text>.*)$")

# Doublings that are ordinary English rather than a slip.
LEGITIMATE_DOUBLES = {"had", "that"}


def unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def yaml_prose(rel: str, text: str):
    """Yield (offset, text) for every English-prose string of one curated YAML file."""
    topic_keyed = rel in KEYED_BY_TOPIC
    off = 0
    for line in text.splitlines(keepends=True):
        m = YAML_COMMENT.match(line)
        if m:
            yield off + m.start("text"), m.group("text")
            off += len(line)
            continue
        m = YAML_LINE.match(line.rstrip("\n"))
        if m:
            if topic_keyed:
                # the key is the topic name; the value is a declaration name or a URL
                k = m.group("key")
                yield off + m.start("key") + (1 if k[:1] in "\"'" else 0), unquote(k)
            elif m.group("val") and m.group("key").strip() in PROSE_FIELDS:
                v = m.group("val")
                yield off + m.start("val") + (1 if v[:1] in "\"'" else 0), unquote(v)
        off += len(line)


def words_of(text: str):
    """(word, offset) for the prose words of `text`, using the audit's own prose cleaning.

    `pt.prose_words` drops the same things but does not report offsets, which a finding needs, so
    the cleaning is applied here and the words are taken from the result.  `pt.clean` replaces
    each non-prose span by a `CUT` marker of its own length, so offsets survive it.
    """
    cleaned = pt.clean(pt.CITATION.sub(pt.CUT, text))
    for m in pt.WORD.finditer(cleaned):
        w = m.group(0)
        if (w.isupper() and len(w) > 1) or re.search(r"[a-z][A-Z]", w):
            continue  # an identifier that leaked out of a code span
        a, b = m.start(), m.end()
        if (a > 0 and cleaned[a - 1] == pt.CUT) or (b < len(cleaned) and cleaned[b] == pt.CUT):
            continue  # a fragment of the span that was cut out, not a word
        if (a > 0 and cleaned[a - 1] == "-") or (b < len(cleaned) and cleaned[b] == "-"):
            continue  # half of a compound
        # `Éléments` and `Théories` are one word each, but `pt.WORD` only matches ASCII letters
        # and so cuts them into `ments` and `ories`.  A letter Mathlib's own prose does not use
        # next to the match means the match is part of a longer, accented word.
        if ((a > 0 and cleaned[a - 1].isalpha()) or (b < len(cleaned) and cleaned[b].isalpha())):
            continue
        yield w, a


def doubled(text: str):
    """(word, offset) for each word of `text` that immediately repeats the one before it.

    "immediately" means separated by whitespace and nothing else: `Cambridge: Cambridge
    University Press` and `Müntz–Szász` repeat a word across punctuation, which is not a slip.
    """
    prev = None
    for w, off in words_of(text):
        if (prev and prev[0].lower() == w.lower() and w.lower() not in LEGITIMATE_DOUBLES
                and text[prev[1] + len(prev[0]):off].strip() == ""):
            yield w, off
        prev = (w, off)


# ------------------------------------------------------------------ bibliography

ENTRY_HEAD = re.compile(r"@\w+\s*\{\s*([^,\s]+)\s*,")
FIELD_HEAD = re.compile(r"(?m)^\s*([A-Za-z]+)\s*=\s*")


def bib_entries(text: str):
    """Yield {key, at, fields} for each entry, `fields` mapping a name to (offset, value)."""
    for m in ENTRY_HEAD.finditer(text):
        brace = text.index("{", m.start())
        depth, i = 1, brace + 1
        while i < len(text) and depth:
            depth += (text[i] == "{") - (text[i] == "}")
            i += 1
        body_at = m.end()
        body = text[body_at:i - 1]
        fields = {}
        for f in FIELD_HEAD.finditer(body):
            j = f.end()
            if j >= len(body):
                continue
            if body[j] == "{":
                depth, k = 1, j + 1
                while k < len(body) and depth:
                    depth += (body[k] == "{") - (body[k] == "}")
                    k += 1
                at, value = body_at + j + 1, body[j + 1:k - 1]
            elif body[j] == "\"":
                k = body.find("\"", j + 1)
                k = len(body) if k == -1 else k
                at, value = body_at + j + 1, body[j + 1:k]
            else:  # an unbraced value, `year = 1950,`
                k = body.find(",", j)
                k = len(body) if k == -1 else k
                at, value = body_at + j, body[j:k]
            # a handful of entries repeat a field (two `year =` lines); the first one wins
            fields.setdefault(f.group(1).lower(), (at, value))
        yield {"key": m.group(1), "at": m.start(), "fields": fields}


def debrace(value: str):
    """(text, offsets) for a bibliography value with BibTeX's case-protecting braces removed.

    `{T}heorem` is one word and must not become two, so the braces are deleted rather than
    blanked; `offsets[i]` says where character `i` of the result sat in `value`, so that a
    finding still points at the line it came from.
    """
    out, offsets = [], []
    for i, c in enumerate(value):
        if c in "{}":
            continue
        out.append(c)
        offsets.append(i)
    return "".join(out), offsets


def flat(value: str) -> str:
    """A bibliography value on one line, for quoting in a finding."""
    return " ".join(debrace(value)[0].split())


def normalise(value: str) -> str:
    """A field reduced to bare ASCII letters and digits, for comparing two entries.

    Accents are written in three ways across the file (`Ale{\\v{s}}`, `Aleš`, `Ale\\v{s}`), so
    both the TeX and the composed forms are folded away before comparing.
    """
    stripped = unicodedata.normalize("NFKD", pt.TEXCMD.sub("", value))
    return re.sub(r"[^a-z0-9]+", "", stripped.lower())


def looks_english(ctx, text: str) -> bool:
    """True unless most of the words of `text` are unknown to Mathlib's own English prose.

    Roughly a tenth of the bibliography is French, German or Russian, and a French word is
    regularly one edit from an English one (`morphismes`/`morphisms`), so a foreign title has to
    be recognised before it is spell-checked.  The corpus is the test rather than the dictionary:
    a hunspell installation may carry several languages, and the corpus carries exactly one.
    """
    words = [w.lower() for w, _off in words_of(text) if len(w) >= 3]
    if len(words) < 2:
        return True  # a single word carries no evidence either way
    known = sum(1 for w in words if ctx.freq.get(w, 0))
    return known * 2 >= len(words)


# Tokens that a citation can be written as: `[key]`, `[Author, *Title*][key]`, `` `key` `` and
# markdown links `[Geck](Geck2017)`.  Collecting every delimited token once is far cheaper than
# searching the tree for 505 keys, and the few keys it misses are then looked for literally.
DELIMITED = re.compile(r"\[([^\[\]\n]{2,60})\]|`([^`\n]{2,60})`|\(([^()\n]{2,60})\)")
# The shape of a bibliography key: a name followed by a year, or joined to a second name. The
# comment audit uses the same test so that `[R]` and `[simp]` are not mistaken for citations.
CITEKEY = re.compile(r"^[A-Za-z][A-Za-z0-9_.'-]*(?:\d{2,4}[a-z]?|[_-][A-Za-z]{2,})$")


def cited_keys(ctx, keys: set) -> tuple:
    """(keys cited somewhere in the Lean sources, every citation-shaped token seen).

    A key counts as cited wherever it appears, not only in a `## References` section: the question
    here is whether the entry is used at all, so the most generous reading is the safe one.
    """
    tokens = set()
    for path in ctx.walk("Mathlib", "Archive", "Counterexamples", ext=".lean"):
        for m in DELIMITED.finditer(ctx.read(path)):
            tokens.add((m.group(1) or m.group(2) or m.group(3)).strip())
    cited = keys & tokens
    # A key can also be written without any delimiter around it; the few that the token sweep did
    # not find are searched for literally, which is cheap once the set is small.
    rest = keys - cited
    if rest:
        for path in ctx.walk("Mathlib", "Archive", "Counterexamples", ext=".lean"):
            if not rest:
                break
            src = ctx.read(path)
            for k in [k for k in rest if k in src]:
                cited.add(k)
                rest.discard(k)
    return cited, tokens


# ------------------------------------------------------------------ proper nouns

PROPER_NOUN_USES = 20
# Below this many words still in question, testing a file for them is cheaper than reading it.
PREFILTER_AT = 64


def proper_nouns(ctx, candidates: set) -> dict:
    """{word: capitalised uses} for the `candidates` Mathlib's prose never writes in lowercase.

    `ctx.freq` is lowercased, so it cannot answer "does Mathlib ever write this word in lower
    case".  The corpus is read again, through the same comment extractor that built it, so that
    the answer is about prose and not about identifiers: `laplacian` appears in lowercase eleven
    times in the sources, every one of them inside a declaration name.
    """
    cap: collections.Counter = collections.Counter()
    undecided = set(candidates)
    for path in ctx.walk("Mathlib", "Archive", "Counterexamples", ext=".lean"):
        src = ctx.read(path)
        # Ordinary words are settled by the first file that uses one; what is left after that is
        # rare enough that most files mention none of it, and a substring test costs a fraction
        # of extracting a file's comments.
        if len(undecided) <= PREFILTER_AT:
            lowered = src.lower()
            if not any(w in lowered for w in undecided):
                continue
        comments, _code = pt.extract_comments(src)
        for _line, kind, text in comments:
            if kind == "block" and pt.LICENSE.search(text):
                continue
            for w, _hyph in pt.prose_words(text):
                lw = w.lower()
                if lw not in undecided:
                    continue
                if w[0].isupper():
                    cap[lw] += 1
                else:
                    undecided.discard(lw)  # Mathlib writes it lowercase: an ordinary word
    return {w: cap[w] for w in undecided}


def collect(ctx):
    findings = []
    source = {rel: ctx.read(os.path.join(ctx.root, *rel.split("/")))
              for rel in YAML_FILES + (BIB_FILE,)}

    # ---- Y1/Y2: the YAML files ---------------------------------------------------------
    lowercase_sites = collections.defaultdict(list)
    for rel in YAML_FILES:
        text = source[rel]
        for at, s in yaml_prose(rel, text):
            for w, off in doubled(s):
                findings.append(Finding(
                    SURFACE, "Y2", w.lower(), rel, line_of(text, at + off),
                    f"`{w} {w}` is written twice: \"{excerpt(text, at + off)}\"", "high"))
            for w, off in words_of(s):
                if w[0].isupper():
                    continue  # proper-noun guard: see the module docstring
                lowercase_sites[w.lower()].append((rel, at + off))
                hit = ctx.suggest(w)
                if hit:
                    corr, dist, uses = hit
                    findings.append(Finding(
                        SURFACE, "Y1", w.lower(), rel, line_of(text, at + off),
                        f"`{w}` -> `{corr}` (the corpus uses `{corr}` {uses} times, `{w}` never): "
                        f"\"{excerpt(text, at + off)}\"", ctx.confidence(dist, uses)))

    # ---- Y3: proper nouns written in lowercase -----------------------------------------
    # Only a word the corpus uses often can be shown to be a proper noun by this evidence, so
    # those are the only ones the census is asked about.
    candidates = {w for w in lowercase_sites
                  if len(w) >= 5 and ctx.freq.get(w, 0) >= PROPER_NOUN_USES}
    for w, cap in sorted(proper_nouns(ctx, candidates).items()):
        if cap < PROPER_NOUN_USES:
            continue
        for rel, here in lowercase_sites[w]:
            text = source[rel]
            findings.append(Finding(
                SURFACE, "Y3", w, rel, line_of(text, here),
                f"`{w}` -> `{w.capitalize()}`: Mathlib's comments write it capitalised {cap} "
                f"times and never in lowercase: \"{excerpt(text, here)}\"",
                "high" if cap >= 50 else "medium"))

    # ---- Y2/Y4: the bibliography -------------------------------------------------------
    bib = source[BIB_FILE]
    entries = list(bib_entries(bib))
    # the header comment, then every prose field of every entry
    values = [(0, bib[:entries[0]["at"]] if entries else bib)]
    values += [e["fields"][f] for e in entries for f in BIB_PROSE_FIELDS if f in e["fields"]]
    for at, raw in values:
        s, offsets = debrace(raw)
        for w, off in doubled(s):
            here = at + offsets[off]
            findings.append(Finding(
                SURFACE, "Y2", w.lower(), BIB_FILE, line_of(bib, here),
                f"`{w} {w}` is written twice: \"{excerpt(bib, here)}\"", "high"))
        if not looks_english(ctx, s):
            continue
        for w, off in words_of(s):
            if w[0].isupper():
                continue
            hit = ctx.suggest(w)
            if hit:
                corr, dist, uses = hit
                here = at + offsets[off]
                findings.append(Finding(
                    SURFACE, "Y4", w.lower(), BIB_FILE, line_of(bib, here),
                    f"`{w}` -> `{corr}` (the corpus uses `{corr}` {uses} times, `{w}` never): "
                    f"\"{excerpt(bib, here)}\"", ctx.confidence(dist, uses)))

    # ---- Y5: entries nothing cites -----------------------------------------------------
    keys = {e["key"] for e in entries}
    cited, tokens = cited_keys(ctx, keys)
    # A citation of another entry is not a misspelling of this one, so the other keys come out
    # before the near-miss search: `Grillet-1969b` exists, and does not excuse `Grillet-1969a`.
    citation_shaped = {t for t in tokens if CITEKEY.match(t) and t not in keys}
    for e in entries:
        if e["key"] in cited:
            continue
        # A key that is cited but misspelt at the citation site is not an unused entry: the
        # comment audit reports that citation, and deleting the entry would be the wrong fix.
        near = sorted(t for t in citation_shaped
                      if pt.damerau(t.lower(), e["key"].lower()) <= 2)
        if near:
            findings.append(Finding(
                SURFACE, "Y5", e["key"], BIB_FILE, line_of(bib, e["at"]),
                f"`{e['key']}` is never cited under its own name, only as `{near[0]}` "
                f"(\"{flat(e['fields'].get('title', (0, ''))[1])[:60]}\")", "low"))
            continue
        findings.append(Finding(
            SURFACE, "Y5", e["key"], BIB_FILE, line_of(bib, e["at"]),
            f"nothing under `Mathlib/`, `Archive/` or `Counterexamples/` mentions `{e['key']}` "
            f"(\"{flat(e['fields'].get('title', (0, ''))[1])[:60]}\")", "medium"))

    # ---- Y6: the same document under two keys ------------------------------------------
    # Two entries are the same document when they share an identifier that names one edition of
    # one work, or when title and author agree.  A shared title alone is not enough: "Local
    # cohomology" and "General topology" are each the title of several different books here.
    groups = collections.defaultdict(list)
    for e in entries:
        f = e["fields"]
        for field in ("doi", "isbn", "url"):
            if field in f and f[field][1].strip():
                groups[(field, normalise(f[field][1]))].append(e)
        title = normalise(f.get("title", (0, ""))[1])
        author = normalise(f.get("author", (0, ""))[1] or f.get("editor", (0, ""))[1])
        if len(title) >= 8 and author:
            groups[("title", title, author)].append(e)
    seen = set()
    for what, group in sorted(groups.items(), key=lambda kv: [e["at"] for e in kv[1]]):
        if len(group) < 2:
            continue
        first = group[0]
        for e in group[1:]:
            if (first["key"], e["key"]) in seen:
                continue
            seen.add((first["key"], e["key"]))
            shared = ("the same title and author" if what[0] == "title"
                      else f"the same `{what[0]}`, `{flat(first['fields'][what[0]][1])[:40]}`")
            findings.append(Finding(
                SURFACE, "Y6", e["key"], BIB_FILE, line_of(bib, e["at"]),
                f"`{e['key']}` and `{first['key']}` (line {line_of(bib, first['at'])}) have "
                f"{shared}: \"{flat(e['fields'].get('title', (0, ''))[1])[:60]}\"", "high"))

    findings.sort(key=lambda f: (f["cat"], f["file"], f["line"]))
    return findings
